name: Install 1Password CLI
description: Downloads and installs the 1Password CLI. See https://app-updates.agilebits.com/product_history/CLI2 for available versions.
inputs:
  skip-if-installed:
    description: Skip installing the CLI if it is already installed.
    required: true
    default: false
  version-number:
    description: The version of the CLI to install.
    required: true
  system:
    description: The system to download the CLI for. Valid options are macos, freebsd, linux, openbsd, and windows.
    required: false
  architecture:
    description: The architecture to download the CLI for. Valid options are universal, 386, amd64, and arm.
    required: false
runs:
  using: node16
  main: dist/index.js
